CREATE DATABASE ParkingDB;
USE ParkingDB;

CREATE TABLE Spots(
	Spot_ID MEDIUMINT UNSIGNED UNIQUE,
    Status BOOLEAN NOT NULL DEFAULT TRUE,
    Lot_ID CHAR(4),
    Spot_Type ENUM('Handicapped', 'Staff', 'Reserved'),
    Geometry_ID MEDIUMINT UNSIGNED NOT NULL, 
    Level SMALLINT UNSIGNED,
    PRIMARY KEY (Spot_ID),
    FOREIGN KEY (Lot_ID) REFERENCES Lots(Lot_ID) ON DELETE CASCADE 
);
CREATE TABLE Lots(
	Lot_ID CHAR(4) UNIQUE,
    Lot_Name VARCHAR(50) NOT NULL,
    Address VARCHAR(250) NOT NULL UNIQUE,
    Num_Spaces MEDIUMINT UNSIGNED NOT NULL,
    Total_Spaces MEDIUMINT UNSIGNED,
    Is_Active BOOLEAN NOT NULL DEFAULT TRUE,
    Latitude DECIMAL(9,6) UNIQUE,
    Longitude DECIMAL(9,6) UNIQUE,
    Lot_Type ENUM('Deck', 'Lot', 'Street'),
    PRIMARY KEY(Lot_ID)
    );

ALTER TABLE Spots
DROP FOREIGN KEY spots_ibfk_1;

ALTER TABLE Spots 
ADD CONSTRAINT fk_lot_id
FOREIGN KEY (Lot_ID) REFERENCES Lots(Lot_ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

SHOW CREATE TABLE Spots;
SHOW CREATE TABLE Lots;

DROP TABLE Spots;
DROP TABLE Lots;